// ===============================
// Ascension Arc — Static Character Roster
// Fully offline, editable
// Image path convention:
// images/characters/{element-lowercase}/{id}.png
// ===============================

const characters = [
  { id:'aino', name:'Aino', element:'Hydro', weaponType:'Claymore', subtitle: 'Clinky-Clank Gadgets-A-Gogo', region: 'Nod-Krai'},
  { id:'albedo', name:'Albedo', element:'Geo', weaponType:'sword', subtitle: 'Kreideprinz', region: 'Mondstadt', affiliation: 'Knights of Favonius' },
  { id:'alhaitham', name:'Alhaitham', element:'Dendro', weaponType:'Sword', subtitle: 'Admonishing Instruction', region: 'Sumeru', affiliation: 'Akademiya' },
  { id:'amber', name:'Amber', element:'Pyro', weaponType:'Bow', subtitle: 'Gliding Champion', region: 'Mondstadt', affiliation: 'Knights of Favonius' },
  { id:'arataki-itto', name:'Arataki Itto', element:'Geo', weaponType:'Claymore', subtitle: 'Hanamizaka Heroics', region: 'Inazuma', affiliation: 'Arataki Gang' },
  { id:'arlecchino', name:'Arlecchino', element:'Pyro', weaponType:'Polearm', subtitle: 'Dire Balemoon', region: 'Snezhnaya', affiliation: 'Fatui' },
  { id:'ayaka', name:'Kamisato Ayaka', element:'Cryo', weaponType:'Sword', subtitle: 'Frostflake Heron', region: 'Inazuma', affiliation: 'Kamisato Clan' },
  { id:'ayato', name:'Kamisato Ayato', element:'Hydro', weaponType:'Sword', subtitle: 'Pillar of Fortitude', region: 'Inazuma', affiliation: 'Kamisato Clan' },
  { id:'baizhu', name:'Baizhu', element:'Dendro', weaponType:'Catalyst', subtitle: 'Beyond Mortality', region: 'Liyue' },
  { id:'barbara', name:'Barbara', element:'Hydro', weaponType:'Catalyst', subtitle: 'Shining Idol', region: 'Mondstadt', affiliation: 'Knights of Favonius' },
  { id:'beidou', name:'Beidou', element:'Electro', weaponType:'Claymore', subtitle: 'Uncrowned Lord of the Ocean', region: 'Liyue' },
  { id:'bennett', name:'Bennett', element:'Pyro', weaponType:'Sword', subtitle: 'Trial by Fire', region: 'Mondstadt', affiliation: 'Adventurers Guild' },
  { id:'candace', name:'Candace', element:'Hydro', weaponType:'Polearm', subtitle: 'Golden Vow', region: 'Sumeru' },
  { id:'charlotte', name:'Charlotte', element:'Cryo', weaponType:'Catalyst', subtitle: 'Lens of Verity', region: 'Fontaine' },
  { id:'chevreuse', name:'Chevreuse', element:'Pyro', weaponType:'Polearm', subtitle: 'Executor of Justice', region: 'Fontaine' },
  { id:'chongyun', name:'Chongyun', element:'Cryo', weaponType:'Claymore', subtitle: 'Frozen Ardor', region: 'Liyue' },
  { id:'citlali', name:'Citlali', element:'Cryo', weaponType:'Catalyst', subtitle: 'Obsidian Opalstar', region: 'Natlan', affiliation: 'Masters of the Night-Wind'  },
  { id:'clorinde', name:'Clorinde', element:'Electro', weaponType:'Sword', subtitle: 'Candlebearer, Shadowhunter', region: 'Fontaine' },
  { id:'chasca', name:'Chasca', element:'Anemo', weaponType:'Bow', subtitle: 'Skyborne Arbiter', region: 'Natlan', affiliation: 'Flower-Feather Clan' },
  { id:'chiori', name:'Chiori', element:'Geo', weaponType:'Sword', subtitle: 'The Thundering Seamstress', region: 'Inazuma' },
  { id:'collei', name:'Collei', element:'Dendro', weaponType:'Bow', subtitle: 'Sprout of Rebirth', region: 'Sumeru' },
  { id:'cyno', name:'Cyno', element:'Electro', weaponType:'Polearm', subtitle: 'Judicator of Secrets', region: 'Sumeru' },
  { id:'dahlia', name:'Dahlia', element:'Hydro', weaponType:'Sword', subtitle: 'Ode and Oblation', region: 'Mondstadt', affiliation: 'Knights of Favonius' },
  { id:'dehya', name:'Dehya', element:'Pyro', weaponType:'Claymore', subtitle: 'Flame-Mane', region: 'Sumeru', affiliation: 'The Eremites' },
  { id:'diluc', name:'Diluc', element:'Pyro', weaponType:'Claymore', subtitle: 'The Dark Side of Dawn', region: 'Mondstadt' },
  { id:'diona', name:'Diona', element:'Cryo', weaponType:'Bow', subtitle: 'Kätzlein Cocktail', region: 'Mondstadt' },
  { id:'dori', name:'Dori', element:'Electro', weaponType:'Claymore', subtitle: 'Treasure of Dream Garden', region: 'Sumeru' },
  { id:'durin', name:'Durin', element:'Pyro', weaponType:'Sword', subtitle: '"The Undying Fire"', region: 'Mondstadt', affiliation: 'Hexenzirkel' },
  { id:'eula', name:'Eula', element:'Cryo', weaponType:'Claymore', subtitle: 'Dance of the Shimmering Wave', region: 'Mondstadt', affiliation: 'Knights of Favonius' },
  { id:'emilie', name:'Emilie', element:'Dendro', weaponType:'Polearm', subtitle: 'A Thousand Scents Traced', region: 'Fontaine' },
  { id:'escoffier', name:'Escoffier', element:'Cryo', weaponType:'Polearm', subtitle: 'Tasteful Excellence', region: 'Fontaine' },
  { id:'faruzan', name:'Faruzan', element:'Anemo', weaponType:'Bow', subtitle: 'Enigmatic Machinist', region: 'Sumeru', affiliation: 'Akademiya' },
  { id:'fischl', name:'Fischl', element:'Electro', weaponType:'Bow', subtitle: 'Prinzessin der Verurteilung!', region: 'Mondstadt', affiliation: 'Adventurers Guild' },
  { id:'flins', name:'Flins', element:'Electro', weaponType:'Polearm', subtitle: 'Shadowy Lights, Stranger Wights', region: 'Nod-Krai', affiliation: 'Lightkeepers' },
  { id:'freminet', name:'Freminet', element:'Cryo', weaponType:'Claymore', subtitle: 'Yearning for Unseen Depths', region: 'Fontaine', affiliation: 'Fatui' },
  { id:'furina', name:'Furina', element:'Hydro', weaponType:'Sword', subtitle: 'Endless Solo of Solitude', region: 'Fontaine' },
  { id:'gaming', name:'Gaming', element:'Pyro', weaponType:'Claymore', subtitle: 'Leonine Vanguard', region: 'Liyue' },
  { id:'ganyu', name:'Ganyu', element:'Cryo', weaponType:'Bow', subtitle: 'Plenilune Gaze', region: 'Liyue' },
  { id:'gorou', name:'Gorou', element:'Geo', weaponType:'Bow', subtitle: 'Canine Warrior', region: 'Inazuma' },
  { id:'heizou', name:'Shikanoin Heizou', element:'Anemo', weaponType:'Catalyst', subtitle: 'Analytical Harmony', region: 'Inazuma' },
  { id:'hutao', name:'Hu Tao', element:'Pyro', weaponType:'Polearm', subtitle: 'Fragrance in Thaw', region: 'Liyue' },
  { id:'iansan', name:'Iansan', element:'Electro', weaponType:'Polearm', subtitle: 'Tempered in Molten Stone', region: 'Natlan', affiliation: 'Collective of Plenty' },
  { id:'ifa', name:'Ifa', element:'Anemo', weaponType:'Catalyst', subtitle: 'In the Wake of Wandering Winds', region: 'Natlan', affiliation: 'Flower-Feather Clan' },
  { id:'ineffa', name:'Ineffa', element:'Electro', weaponType:'Polearm', subtitle: 'Boom Boom Thunderwave', region: 'Nod-Krai' },
  { id:'jean', name:'Jean', element:'Anemo', weaponType:'Sword', subtitle: 'Dandelion Knight', region: 'Mondstadt', affiliation: 'Knights of Favonius' },
  { id:'jahoda', name:'Jahoda', element:'Anemo', weaponType:'bow', subtitle: 'Windthreading Shadow', region: 'Nod-Krai' },
  { id:'kaeya', name:'Kaeya', element:'Cryo', weaponType:'Sword', subtitle: 'Frostwind Swordsman', region: 'Mondstadt', affiliation: 'Knights of Favonius' },
  { id:'kachina', name:'Kachina', element:'Geo', weaponType:'Polearm', subtitle: 'Mottled Gold Yet Unsmelted', region: 'Natlan', affiliation: 'Children of Echoes' },
  { id:'kazuha', name:'Kaedehara Kazuha', element:'Anemo', weaponType:'Sword', subtitle: 'Scarlet Leaves Pursue Wild Waves', region: 'Inazuma' },
  { id:'kaveh', name:'Kaveh', element:'Dendro', weaponType:'Claymore', subtitle: 'Empyrean Reflection', region: 'Sumeru' },
  { id:'keqing', name:'Keqing', element:'Electro', weaponType:'Sword', subtitle: 'Driving Thunder', region: 'Liyue' },
  { id:'kirara', name:'Kirara', element:'Dendro', weaponType:'Sword', subtitle: 'Cat Upon the Eaves', region: 'Inazuma' },
  { id:'kinich', name:'Kinich', element:'Dendro', weaponType:'Claymore', subtitle: 'Turnfire Hunt', region: 'Natlan', affiliation: 'Scions of the Canopy' },
  { id:'klee', name:'Klee', element:'Pyro', weaponType:'Catalyst', subtitle: 'Fleeing Sunlight', region: 'Monstadt', affiliation: 'Knights of Favonius' },
  { id:'kuki', name:'Kuki Shinobu', element:'Electro', weaponType:'Sword', subtitle: 'Mender of Tribulations', region: 'Inazuma', affiliation: 'Arataki Gang' },
  { id:'sara', name:'Kujou Sara', element:'Electro', weaponType:'Bow', subtitle: 'Crowfeather Kaburaya', region: 'Inazuma' },
  { id:'kokomi', name:'Sangonomiya Kokomi', element:'Hydro', weaponType:'Catalyst', subtitle: 'Pearl of Wisdom', region: 'Inazuma' },
  { id:'lanyan', name:'Lan Yan', element:'Anemo', weaponType:'Catalyst', subtitle: 'Spring Woven From Jade', region: 'Liyue' },
  { id:'layla', name:'Layla', element:'Cryo', weaponType:'Sword', subtitle: 'Fantastical Evening Star', region: 'Sumeru' },
  { id:'lauma', name:'Lauma', element:'Dendro', weaponType:'Catalyst', subtitle: 'Evermoons Sacrament Song', region: 'Nod-Krai', affiliation: 'Frostmoon Scions' },
  { id:'lisa', name:'Lisa', element:'Electro', weaponType:'Catalyst', subtitle: 'Witch of Purple Rose', region: 'Mondstadt', affiliation: 'Knights of Favonius' },
  { id:'lynette', name:'Lynette', element:'Anemo', weaponType:'Sword', subtitle: 'Elegance in the Shadows', region: 'Fontaine', affiliation: 'Fatui' },
  { id:'lyney', name:'Lyney', element:'Pyro', weaponType:'Bow', subtitle: 'Spectacle of Phantasmagoria', region: 'Fontaine', affiliation: 'Fatui' },
  { id:'mavuika', name:'Mavuika', element:'Pyro', weaponType:'Claymore', subtitle: 'Night-Igniting Flame', region: 'Natlan', affiliation: 'Scions of the Canopy' },
  { id:'mika', name:'Mika', element:'Cryo', weaponType:'Polearm', subtitle: 'Coordinates of Clear Frost', region: 'Mondstadt', affiliation: 'Knights of Favonious' },
  { id:'mona', name:'Mona', element:'Hydro', weaponType:'Catalyst', subtitle: 'Astral Reflection', region: 'Mondstadt', affiliation: 'Hexenzirkel'  },
  { id:'mualani', name:'Mualani', element:'Hydro', weaponType:'Catalyst', subtitle: 'Splish-Splash Wavechaser', region: 'Natlan', affiliation: 'People of the Springs' },
  { id:'nahida', name:'Nahida', element:'Dendro', weaponType:'Catalyst', subtitle: 'Physic of Purity', region: 'Sumeru', affiliation: 'Akademiya' },
  { id:'navia', name:'Navia', element:'Geo', weaponType:'Claymore', subtitle: 'Helm of the Radiant Rose', region: 'Fontaine', },
  { id:'nefer', name:'Nefer', element:'Dendro', weaponType:'Catalyst', subtitle: 'Secret Beneath the Sands', region: 'Nod-Krai', },
  { id:'neuvillette', name:'Neuvillette', element:'Hydro', weaponType:'Catalyst', subtitle: 'Ordainer of Inexorable Judgment', region: 'Fontaine', },
  { id:'nilou', name:'Nilou', element:'Hydro', weaponType:'Sword', subtitle: 'Dance of Lotuslight', region: 'Sumeru', },
  { id:'ningguang', name:'Ningguang', element:'Geo', weaponType:'Catalyst', subtitle: 'Eclipsing Star', region: 'Liyue', },
  { id:'noelle', name:'Noelle', element:'Geo', weaponType:'Claymore', subtitle: 'Chivalric Blossom', region: 'Mondstadt', affiliation: 'Knights of Favonious' },
  { id:'ororon', name:'Ororon', element:'Electro', weaponType:'Bow', subtitle: 'Shadow of the Night-Wind', region: 'Natlan', affiliation: 'Masters of the Night-Wind' },
  { id:'qiqi', name:'Qiqi', element:'Cryo', weaponType:'Sword', subtitle: 'Icy Resurrection', region: 'Liyue', },
  { id:'raiden', name:'Raiden Shogun', element:'Electro', weaponType:'Polearm', subtitle: 'Plane of Euthymia', region: 'Inazuma', },
  { id:'razor', name:'Razor', element:'Electro', weaponType:'Claymore', subtitle: 'Wolf Boy', region: 'Mondstadt', },
  { id:'rosaria', name:'Rosaria', element:'Cryo', weaponType:'Polearm', subtitle: 'Thorny Benevolence', region: 'Mondstadt', affiliation: 'Knights of Favonious' },
  { id:'sayu', name:'Sayu', element:'Anemo', weaponType:'Claymore', subtitle: 'Mujina Ninja', region: 'Inazuma', },
  { id:'sethos', name:'Sethos', element:'Electro', weaponType:'Bow', subtitle: 'Wisdomss Measure', region: 'Sumeru', },
  { id:'sigewinne', name:'Sigewinne', element:'Hydro', weaponType:'Bow', subtitle: 'Wondrous Dragonheir', region: 'Fontaine', },
  { id:'shenhe', name:'Shenhe', element:'Cryo', weaponType:'Polearm', subtitle: 'Lonesome Transcendence', region: 'Liyue', },
  { id:'skirk', name:'Skirk', element:'Cryo', weaponType:'Sword', subtitle: 'Void Star', region: 'Fontaine', },
  { id:'sucrose', name:'Sucrose', element:'Anemo', weaponType:'Catalyst', subtitle: 'Harmless Sweetie', region: 'Mondstadt', affiliation: 'Knights of Favonious' },
  { id:'childe', name:'Tartaglia', element:'Hydro', weaponType:'Bow', subtitle: 'Childe', region: 'Snezhnaya', affiliation: 'Fatui' },
  { id:'tighnari', name:'Tighnari', element:'Dendro', weaponType:'Bow', subtitle: 'Verdant Strider', region: 'Sumeru', },
  { id:'thoma', name:'Thoma', element:'Pyro', weaponType:'Polearm', subtitle: 'Protector From Afar', region: 'Inazuma', affiliation: 'Kamisato Clan' },
  { id:'varesa', name:'Varesa', element:'Electro', weaponType:'Catalysm', subtitle: 'Strength in Serenity', region: 'Natlan', affiliation: 'Collective of Plenty' },
  { id:'venti', name:'Venti', element:'Anemo', weaponType:'Bow', subtitle: 'Windborne Bard', region: 'Mondstadt', affiliation: 'Hexenzirkel' },
  { id:'wanderer', name:'Wanderer', element:'Anemo', weaponType:'Catalyst', subtitle: 'Eons Adrift', region: 'Sumeru', affiliation: 'Fatui' },
  { id:'wriothesley', name:'Wriothesley', element:'Cryo', weaponType:'Catalyst', subtitle: 'Emissary of Solitary Iniquity', region: 'Fontaine', },
  { id:'xiangling', name:'Xiangling', element:'Pyro', weaponType:'Polearm', subtitle: 'Exquisite Delicacy', region: 'Liyue', },
  { id:'xianyun', name:'Xianyun', element:'Anemo', weaponType:'Catalyst', subtitle: 'Passerine Herald', region: 'Liyue', },
  { id:'xiao', name:'Xiao', element:'Anemo', weaponType:'Polearm', subtitle: 'Vigilant Yaksha', region: 'Liyue', },
  { id:'xilonen', name:'Xilonen', element:'Geo', weaponType:'Sword', subtitle: 'Ardent Flames Forge the Soul', region: 'Natlan', affiliation: 'Children of Echoes' },
  { id:'xingqiu', name:'Xingqiu', element:'Hydro', weaponType:'Sword', subtitle: 'Juvenile Galant', region: 'Liyue', },
  { id:'xinyan', name:'Xinyan', element:'Pyro', weaponType:'Claymore', subtitle: 'Blazing Riff', region: 'Liyue', },
  { id:'yae', name:'Yae Miko', element:'Electro', weaponType:'Catalyst', subtitle: 'Astute Amusement', region: 'Inazuma', },
  { id:'yanfei', name:'Yanfei', element:'Pyro', weaponType:'Catalyst', subtitle: 'Wise Innocence', region: 'Liyue', },
  { id:'yaoyao', name:'Yaoyao', element:'Dendro', weaponType:'Polearm', subtitle: 'Burgeoning Grace', region: 'Liyue', },
  { id:'yelan', name:'Yelan', element:'Hydro', weaponType:'Bow', subtitle: 'Valley Orchid', region: 'Liyue', },
  { id:'yoimiya', name:'Yoimiya', element:'Pyro', weaponType:'Bow', subtitle: 'Frolicking Flames', region: 'Inazuma', },
  { id:'yun-jin', name:'Yun Jin', element:'Geo', weaponType:'Polearm', subtitle: 'Stage Lucida', region: 'Liyue', },
  { id:'mizuki', name:'Yumemizuki Mizuki', element:'Anemo', weaponType:'Catalyst', subtitle: 'Embrace of Enchanting Dreams', region: 'Inazuma', },
  { id:'zhongli', name:'Zhongli', element:'Geo', weaponType:'Polearm', subtitle: 'Vago Mundo', region: 'Liyue', }
];

// Helper to resolve character image path
function getCharacterImage(character){
  return `images/characters/${character.element.toLowerCase()}/${character.id}.png`;
}
